MOZ_ENABLE_WAYLAND=1
CLUTTER_BACKEND=wayland
QT_QPA_PLATFORM=wayland-egl
ECORE_EVAS_ENGINE=wayland-egl
ELM_ENGINE=wayland_egl
SDL_VIDEODRIVER=wayland
_JAVA_AWT_WM_NONREPARENTING=1
NO_AT_BRIDGE=1

# Prioritize 7900 XTX (card1) then Integrated (card0). Ignore NVIDIA (card2).
WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
